// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tasks

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          int64
	Title       string
	Description pgtype.Text
	Completed   pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}
