// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package tasks

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO tasks (
    title, description
) VALUES (
    $1, $2
) RETURNING id, title, description, completed, created_at, completed_at
`

type CreateParams struct {
	Title       string
	Description pgtype.Text
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Task, error) {
	row := q.db.QueryRow(ctx, create, arg.Title, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT 
  id, title, description, completed, created_at, completed_at
FROM tasks
ORDER BY created_at
`

func (q *Queries) GetAll(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id FROM tasks
WHERE id = $1
ORDER BY created_at LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	err := row.Scan(&id)
	return id, err
}

const update = `-- name: Update :exec
UPDATE tasks
SET
    title = $2,
    description = $3
WHERE id = $1
`

type UpdateParams struct {
	ID          int64
	Title       string
	Description pgtype.Text
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update, arg.ID, arg.Title, arg.Description)
	return err
}
