// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeUserService() *UserService {
	dbName := _wireDBNameValue
	appName := _wireAppNameValue
	logger := NewLogger(appName)
	userRepository := NewUserRepository(dbName, logger)
	userService := NewUserService(userRepository, logger)
	return userService
}

var (
	_wireDBNameValue  = DBName("user_db")
	_wireAppNameValue = AppName("APP")
)

func InitializeTaskService() *TaskService {
	dbName := _wireDBNameValue
	appName := _wireAppNameValue
	logger := NewLogger(appName)
	taskRepository := NewTaskRepository(dbName, logger)
	taskService := NewTaskService(taskRepository, logger)
	return taskService
}

// wire.go:

var appProviderSet = wire.NewSet(wire.Value(AppName("APP")), wire.Value(DBName("user_db")), NewLogger,
	NewUserRepository,
	NewUserService,
	NewTaskRepository,
	NewTaskService,
)
