// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"github.com/khhini/development-sandbox/golang/waca-go/internal/server"
)

// Injectors from wire.go:

func InitializeServer() (*fiber.App, error) {
	app := server.NewServer()
	return app, nil
}

// wire.go:

var serverProviderSet = wire.NewSet(server.NewServer)
