[package]
name = "file-io-patterns"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
